name: iboxpro_flutter_example
description: Demonstrates how to use the iboxpro_flutter plugin.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter_signature_pad: '3.0.0'
  barcode_widget: ^2.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  iboxpro_flutter:
    path: ../

flutter:
  uses-material-design: true
