name: iboxpro_flutter
description: Flutter плагин для работы с библиотекой iboxpro
version: 1.0.1
homepage: https://github.com/Unact/iboxpro_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  meta: ^1.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.unact.iboxpro_flutter
        pluginClass: IboxproFlutterPlugin
      ios:
        pluginClass: IboxproFlutterPlugin
